language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  provider: s3
  access_key_id:
    secure: mA2KOCvRqZkNcSUM+cx83vzG7K8hI/qZAdq41pxFQ9W6tXqFoNBFhbzXbc1JA3CzcKuFQTkSwOsVGGU1J5lwQN8P+580llLA36GJ/AivFHU8/EO0GmIwJgjVzE5o4tnje9kfnkgKbpFS3aIY6tJkucQoXAobv8lfiXeZ1FL2SKkMeM/R4RCbwtqRiiNbQ0/V59MldxbCDmWjZ85Or6t+j3tLAEPdXunvVlZf7Q6bGYxJu4yzyuANsPjaAbo7zfolyugZada4Vp1uxAVj0KHuA1PuNz6mnWYHgsLE5RF0cBFTZd2RNwuxUOd0WWxulACYa28KUTcm1ppgNT560sPVW4lwXmJwrjixx2lPCVKMLjpmv/1HwvhROQZ8DdQcerBY1VkYX3QmPw5mr+paxEfX+BkFQKRCbGKnrhwf7rhjVUSf7pFzgqZYZsLMNPWmm0BYs1w0QPYkgW2takyfQ7GS4kxNiP8X3oq4RE3xBupFXcz24jHV0Q9I+lCE77UriuEqqcZPfIHwQYM0IrkOoDF8Yg1IGvW79KOiDv5/UVl93Y1NzUwZD4WMr30rfd6PDqbr16rTntQvSp4h4uG7DnAyWJkZeH3w5qoT28nB/7nf/DAVSm0dAghBrtyyBJj1+OZcczrkMIwri+GrNwPVOKHQByzFvf6R4CvROfKHCWL2xO0=
  secret_access_key:
    secure:
    ZAqVRUdG4AyNNaECv8q7SJkKy5tbS6lLP623rniXb1LvSe9FkNJCgzd3ZmLu6/3QSrUoqynogiRiincyuvE7cR5BZ5t70DnTP/fwX2YMZce9qZUntYJx7Xj0DZp1U6x2NtYuB5aoFvHtEZSgXG5RRf/NYilUiIkRJ0S3GUzd7Q4Kd2s64kq5CtjPxuYFQuOTEF4WHUHBrD2M/PT2WmovWFyVhE/MOE4SfkXi1Qr0CJQG+lGf1PVewgGttntoZMoh8nn/n8jAIqwztOAYDmYsGLMT0RZ//HOvXkRR6tFMlLZE3yJAN9VY8zeTnn/nTAe+K/yJtvQmYLDItxvGAeoz6bBO9IDESKv4IG5eLvqplqVbWFneq2DVHo9u0xZLuT6Uv0Og8G+pFA/RN2RuIMGSXzq1IybXy81rK9xUu3RBr8maMmggDEvc369hM0XW4FD4A0ApfLZNPS9+2oskSmMGwMq6mQW0HnjqChHKIsXED8SirtJr7EUUnUPHDb5TcpbFtwJQhBYThDgvWll0bazeZvfDvICb6O5lvCLRhdeQ/ppvSUVsz3jkfUhFz3IuKxox0c6RQMKOvnvQTiBMoulSiUe1hDd6aZR6B1ux2mP7NcOygWk9khPUV9Uw1kiVLPLlkXA/gkdJP7a05hmNg/8dEs2w6mE+u/RqQCU07EIGogk=
  bucket: dilyan-test-lambda
  local_dir: "./target/scala-2.11"
  upload_dir: travis-builds
  skip_cleanup: true
  on:
    tags: true
