language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/simple-deploy/deploy.sh $TRAVIS_TAG"
  on:
    tags: true
env:
  global:
  - secure: mEZJxq6tATkba0KqgjYP00z+MxzCKW1rN/SxXobAREcgpkfIDXlnj1q+Wgxwed1yhd24yu3mWIWrt/6uU5BD6Lmff2ZribQvj0xYuftrBj+0iP8oJw4NJ/WUI654atepOD7ZNzFYyUGycQd2zmJ/td0b7GBLNo128TttINnmF1lqHvSeTo63pP48xAJ1X9mOBxUZgQ7z6YxmIel8MOgQy/ghYhoEryJquPx2NAPGRX79sfxC3qEVmvPYjwnkaTU5MEbF0kSxX+fdBBxqCMYWoV/YDbvefmT9Y51qoATRYsBpN47rA6+4zb3UT+tmbgeo/vceSXC5du2skaM9f+2djttEc1J0DX9nwnWQJ+ti6ExEYGLCa1ufIary8jUg8vtMGNlH8DfAY9gTZsU22tpGZStN/z+uuGW5baJarfakMI2OpXOkMfnsObe4cyGCL0RMSDuPXtWcCkFIf+Ra0cL7lXphCyPi+Be9wJYRqfI5rolF6dY5gLRrz+QCYp5huBbpElA8o1wBAriowvY2EkH1Q6LWmD0ykG9dy00EJv+Mw2jHcN71IzWVPGcdUsPCIEWgqvJxNEdsYVq9OIyleKXyWo06nGQgTdix9PftRvBrWsRf6+wYQbrdrQ9f4yJpObPERt/L95/GmmNliO2tqL+s1IKIMM6PmzpnWhcuNdMIovQ=
  - secure: q4Bc+3G0OUJsmBtAAw6gyrWeMylUh2BKeAbADu2k8j6Uc5EUThLsZ5e+0SfvXK9u1OcgQTmkTquIamULr10r/5FhygZQMN8fn+2A0CuVrpNhzTAH/3cU23oycDLBMezwR5dFUDl8c5uzEsJLf5H/54TNTs1GQpbimQyycl8VXW1GhyjB4+nSCH+o+8u+QMLbs+PD1zRnN626gU3j28Dg7PlrEw/hQa4SEM9zOWdTPBy6Otm3Zkg6FVCPGOVYUQTR3rBVALBz6PGrafNPVPbaSh4Hro6J0PeJkrJZcVxXVMFXHDj0aqI+nL+OONfivADcSU1Lg1h0dTlznInbXCztz6tzw5+rdwzCaIUWLq27eh4V9FDvPCZQiNCOdkrrh5/KYK8pHqVn3GJ5QejzmamRcZ9RqdguUINCoQkl7OFHnAWjQaQ0XvwXjolhwwwL29Or7ZQvlLq2ncsZUuYqPW2K4k3xLv6sqWvrd6lvnOIPm3MABWXVzlBZ8kcjiS8QXjMLZmjRK8zCnLu2TeYc7xVTmMXPhYdI0lKQ0Cjtgo2iAfhjdO9ywvM1JH23zjMQYiihNTK6CxtY0ZHEG4K0dg5tPQYoc+eI0V2zgAWaU0be4FncYENSEHIgg1Yyn6KR836gaUAmiiDXA1ZmY5yBlT5EBRVrBPIZTE1/djcJSP2m/pY=
