language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
before_deploy:
- pip install --user release-manager==0.3.0
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    tags: true
env:
  global:
  - secure: Gn4cNgpsodqf6+jXrDc9WI3xF3y5LFHlXy4pjOVDuWn2zkqGBl5Trf6EJ9iZIK9uBfc17e3zp258AOa1FEtGXLqHyZD42mpFdDf4X45Dw1bc9q48huuDSukWahUxex0wENanyP6s9GdQlNBZO9iRVL0U7SQm2tGcdo4MTInmz2nPpxrwbRsBMi3x+JEf8lRv2PxhKRVdkkWccgQdRsqKywGY+VTVCF5eXiJrW7mqYdKu90q5gRNRq5WBQQyZU4qBpctlI0EuJYLEQxOslFR9jfG65cgDP9XiOhuC8+UzooN4T8+A8dhylBreYSbdFpKGmZOlEA0VfGw2ZC8i+z8kFVNW2AQM6eu6uFMUTw9wSj8FNROGGhW1z8LTLjEcqQsuobmrEZURgqs65U12A3Eq+BLZ+TCCzKAAL5Kr97r0xSjZoPkadZ+rl/AZc67HL5jfqenD6J6aPlMsXEfO1U+sVq61Q2ljEbqa6dltuPSyWgE7/a/0fwlVTIzOjkusitvGrIYX8kYJDCrBcXV+aPZpmDB1g3PKeNq+A7iAnucaBmQ64vCEubftLOCITtlfy7CPHRhOlvy0EmZRJmB5+9UqFtv9/X3dkRMWEUSSP3tosJD3g91mBLpCtdDUi8y1IPgOB6OVRcWPIWWtJT0DEsleE+EJEcszCTK5mbpLjN/u/9Y=
  - secure: hCv5mtbhQk0qNojq/1CKxRy66yfeti6oqYSVJxps7Hr0xKX7dzXZpU61zT5TfSEtRntBvrCHV19kcDT35caIvxP6BOr//m4YCXPzifJ4aL5AqVu+Bx0FZJk1P3ZU8WeGl7ipVKLJ0lLDxs7kDkxZ3Rem7gdT9ZlaMZRNYK+vPF1TMexKcvO2slIQzsGnGxSuu80DC089vwPcVXNdmHtURRXKxjOY5eV2zH3ZTq5kxOmdtpEH3+gquhAbp8YJSLFVem3QmbSYm9XstCZIKowHwHA4ouKXROSJpr3Tz+ia0p3KkzYHKhICsN1GjvijD/pdOFnTg/Be1LuM10Y7gtMB0K92k5R0KYEe5vsd1YMt5CzUDCFm1V23eDi9FydAaJACVwQNLE9fTZiJH/nGGQt1Ei8fpZHudnINiODekc6dzHsasOqkYGBLErGYgvlZ6S3stFgvtesxdR9aInO54b/XdnX1k7DFV8O37UV1IbjVQIdtNThzYpZYvP75pHtA5jlOSqISRrRnrA7vKapJTZcgjr3xVplbsrw49fP/BCc5rpuU345lgGEntvHoxyrPorQc5VXcTuZGFoJkfvQV9fqG0oJuDnCus/qPDBdTUpd8cAJ+MfniNv3w3G89VTWGJzKbs82AkXjXcEdmzxMOM7O38azoS+kVoRo+zIv38RVYoM8=
