language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
before_deploy:
- pip install --user release-manager==0.3.0
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    tags: true
env:
  global:
  - secure: H4VpSVhpAdtP2mtizBmHCie7Iv2XOfaTpV1uI6rairTh+A8ZzRIV1jaGlCBP9isAjp51R6XkIc+jME6SXu7RKoYLvcXDca3r7Macy90e8eGw3UZiVxUgA9p1biffIllHUV40C2urHg2VM/pH09ddfctAAhvZ88WY7M8zPlem1dL2n7Jdyjmycx9Mfdvy6zSr4AZz/CEt0NFKRJ1vKbj7E7XuClPE/eNewRRarUPoEN2ljtmOlB3QtaZYRJD4H2G2h2qI1fRf1Y3tQvxpWExb+vPYtnAk3SZbwJSKroeGaw1brkx60fgOlWj6sYclX5poQDQeNlaS1C0/tEE8rAZVGMB+GPeG8j3A1v62L9tV4rajN+uHog7mQa/PsKohdmJtxEobpC/ALrAAW2Z5ZgGpr5BO55Iu/PO0ZbQrVruwjh7jlVw4LhnyGipMRmlxINeyYJQGfpwjzGr3DJ453Q10oITUK6ySDZ4j+GNKgIDsm7sHYHI9Y429sV/r+nJ1fz5J1OIWF1kHtNMVQ8uyISRMhnSktME9eQV0sCHn+XjSUlWg5E18dBq4LnjOhymucPyBWAoMjtIJaeWEjHs5ZvaP92fj0D39RCDRuvg3c7UvVNQQ6eUD6uQXaRikLdi2o02+ahvc9qBlkXUjJ2HojqM+LBSqwZr1SLhBJ5ql4Z4fHaM=
  - secure: KU/GkXQ+C1MsbDh4Fe27INyh7ov8UXP2aKNOoJaBy0KlavtmpJcerPjDoO3MdmpyDLiFtQQTSEka/8oYv9FUCFIXexRSUtj6WfGa9Z5rLVrzhOaardQA8d52NsccKoqOefGon1gcacKVnDUclABHV8p4KYcbj/y3yS8EW7aDw288DPfF6B9QMBZmHhLsXx2n8PD2ocOZ5py3+uH97iX3OKhEH2HxFKpP2VGsDvTczS2Ckk/6wwLmBFQSv+BA1BJYYPzCCIRylUZDKmRaSWiAZDVRwJJN61mtAA5LVa6O1KYLwqjhJycc6X4dN129f8Npuk/qoITRmd+Tvxgt5b/1aKDGfbjGzdTnxVmcaq3DA8An95erAX9ojE2b3ucmHvompTCeqiI2T4fmdfwfBRUO6lFZjrgyCePFYQPCuGVqdjgi6+a5d0qmuP46EdP8UWYIfGNOBctMNY4YQNVocCdQLbYEe1oDhRDIEl4PH3uHgjRPLOrUc2paTryN7aBzgVY0esCwtPmRNWLct2vVXHhM6eJXeqWUlaAh+pRryywBge3/6vRCFOkx5cu7HmxPYRS+vaQXMc+kB3oQKDoIt1Z5yaSwrsdeihEi+N+KwHttb/3QDBMnAfQ+ct2Bpq/OOXiyLY3jupBufa8IQ7eWRTAM8SwBqRlH+g8fBNki2koOpAY=
