language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  on:
    tags: true
  provider: s3
  access_key_id:
    secure: u4LwNu/cMch7KBHg11KsJV4y2TffsUGeSappITGEDjxTWistNaGauKuAwL0S2TEdpLKyMeUGYHCRHsEIfKXepMc0FLVmb5btqGVDrM1XQKqT4xcBshtRibpCvdbHfcbT8rnqaiKic0424e2yDxbpuaqZhVywtGQIFWBCrj56utDq/2klpk/AtMKRmvHK1y/ZDBD1xxq31a+lZZ28j2zkj6rRQC0RS1aCHlRCuKjd+romM5/4oXZxB6TN0CI724HxnqCe957Zxwe/ZoBQV9HqoV6BFqpG47I+30pHJ67bvfY8aFTixVf72HD8habskegyZF4JUBGqFtG0cTD4cxDKXXgOA6XL4hC2gAMJRL62iYVkip2VCNaoL/crJYrYwBJl3ckzw8j62Pq+18cxFxpNWQpC8xYf6KQD3+DJFJu01e2De9iLuoZ62LJ+3emI5LHTyDSV5Eh0vau1nOhXFVvk4kSLC/3Lt6MWZBP2AuHiVnKrHtl6lCZ0qv43BoQP/1N0Yvom0zZVFyknu3ZEdvUzi66vmJNshGKRtBTNe/gzNIjwyRBUMMyyykqeDTah+ZfeJkf5BmRfS3FaqQ/BvPoKrPHqIrTzwi/0n/MabCpXVVByIOip1XKm5Hq4etKg/gPNYnK70wC+UMKb4761K32saPPTg45Imhlc+Aix7OrsyHE=
  secret_access_key:
    secure: smMj21S0+CrNGQC/bovYEvo+ycT9B+P+Xeg74hGBh8ZbEhrC0RVhYhJ1+FiY4Zy5CDBHcRzcWdOc2fpGZrP/69PgGUDh6P0d1MatnHSKA67aj97B995rMo8qqJ5l6XJNocy6evWD2vhFcA43Y9frA9HlgDKP73oVCQA3w/8NS86ia7G8cjty/6/L1VFfzRGglkPnbmoA8E3Pq1xh1EgVrRMNG/Gg0AzgpcB1u/ESeUEZcDjnS1O2GLOVd531O/3toylp52YyRuxUj2qrKkF529a7kiLYhKsXN1yr35kb2tQsQcVOeaNY9Qf3aMC5IideErckRm1vlVdzP/0SN2ecIN+ovtBK9smOYtX47Fn2iVN5ObJve+/Uepg/7fACWG0/zA5XovJElkUQFIBcU0ni1AMuLqEJITXRle3JQBxUT9F/+ek9rju82VjSitfb4u2LPKv+GezNEsdAlu3bP4Pp1SnCuQ6ZM7tUmkguFIGzmd6k3W/Wu3GVLh1HQaRvvIh8a/rQ6uhbsKSn81+lMxiQ4vVSl3t5kSsLUPIvXTQd83HxYLQ18Fj3isGT+j4up/btPlf/UKtkYrRPnpnJvnP3XXxYIEO5S+vWy5JgKNSzTl9aW9QBMv+M770uey2HzrvpkRYTJivp0pgUATjybXSTLR6H8wdkXzzsq7sbiH6tL2c=
  bucket: dilyan-test-lambda
  local_dir: "./target/scala-2.11"
  upload_dir: travis-builds
  region: eu-west-2
  skip_cleanup: true
