language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  on:
    tags: true
  provider: s3
  access_key_id:
    secure: lqtfclCojHCuE2Sct0FKh2wRVfqTGKdPgp8m9VyWRqcA2Iob5WvgKUCKtg12OFioxP34zt6Z+3Qe6IKtOzEN/zFkTzszPYqVT895Yl0zdiYhgkEZ4Fk52DANXB7cRuxADGwhw4Y17epNE7zItyoTkr1E6kXIKlrxEJoya9hOMqoW1sLhpw89+7/p4uwvjDXDpu8Ox7i/iZYWhVATbJoJdQoy5DRq2HHwb4dUXDHT9VcH70x9rwweDlNwvHOddd6nk06grhb1RV3azI+ngo7r5OEI3N1H2aF7Sj9u3a4JhNIz7v5L5lnuwBM3WU8KdODb7uIhXIgQdQRyHKbE8RUcsydd3+yE89zcY/b0NaDgXQv3P/ZkcuhuSemH24al4bIJ2K3vi/8DK313oGKPoZtIIrvG86pgt9RJSlFb8KPDho9KhX3AwYC/XGcS5pscSaxTxaDfS0BdPJ/SNEi7MUTdLDw60kEmI6d4OV3uVQIRECShuy0E7TCXSVfMvfQ1xoMj5Bp/GTWtEGjhgmNTlDjo4f4n190Ky6OOfOb031EVYbIGBm73aiaSbwOlpQjaA1V4Y/rRXvqIuf4fpo3aoP3dAH22SrrmKz/hPdAItYUNMsLyR4+mUcFvKl/z2rNm5FTkc+MTe6UlXP8G74c4IwsRvK+ARLG/jmmMULzjM9dqS0M=
  secret_access_key:
    secure: MSl4Ek0v+q4Natww7NQ2wOMCgp5piCoeJ0c4HZHJgmlxWIQF0YKZD8WOYsXJARJuSDXpm9ZfzgBBURZwd9dvaOn3BtowuGWDXWa7xL4xTyjJ+g7U+mQQyPxY3RaRNP4EudQfCO+Z2yKFZd2mfAHfiQrW2WcNHX8JFM4UOwS4LQj11YDGfiZrkI3bQHXtigV16zvh9UsoBWvH7/TqzvWBC+j3NF6pSMyAyTo//BKzGN/PlujfcS9aXov0M7tRtjztel5Ah2XDQaOnwhC15qt+0ly4G3Idch0cqtnq+OyDWFldPdWkHZo9ofL6e/t1bGxITHWDEzEKKpRCZRbr+ztgk3/kyt46+jgPYAmG1ZqzdrjJaLWWSLjqXOxjF4eABvNntdmVklXNhVD4E0M2+rlaBywuC/FDqXetXPq6wXwmasbfN+CBNA8wqaADF6PQypcMSh57E4GSnyBGIzF8y+asP0z/8m1/ZiO6XdpoH83uMEmVq3WePO4lAA6RaNWo+Gwj7FhEuClDODiMSaufR80FgAMpVSNUB6jeFcxXLjes4p9eGSXxql6cuMMeAukv+8p3zy6PVVrkdMK9LKi8Ycs9HMBAfRXVu402/DFUvTX8dzg+hw00g8YhPkNFPcKTqc3FGaqwmlyjy2TSOnh/8IUIKF5o5GvFKDwP3HmK6UveLdM=
  bucket: dilyan-test-lambda
  local_dir: "./target/scala-2.11"
  upload_dir: travis-builds
  region: eu-west-2
  skip_cleanup: true
