language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
deploy:
  on:
    tags: true
  provider: s3
  access_key_id:
    secure: nx4SQlV0IRVe4Je3vmg06mnDk8vfXwMtIZKJn328YKorhcfWt12W7gO8cX2BRKyND7FRz7y6KqDcesLc7hgwa5tgUk8iWYyxhDZSQGYA9RtdSEJNiSor5/e7gItw1ZHXWrhr/yNPFNS69wOcwJvS324rZdJ4Djq8fzN5EAC3Yy6XOCvzwCy1wwPyFYiHn/kIO3nzIId2I7QCjwLqGORh5rcjHFsycI8bGpzrMNDfPOQXIotZJ02uKKon/OaIdteG1txNZlvgGTiJE77w5USj2setEo/bXsV21wGF05H8q/Wqd89zoNt/XWcQsEIXxdiJlY+M6gvgo+m3yd3gF5cYrY3mm14Kr9k3bnpW7n8JKsN4rSnNISoAaQCt1vJa9G7o7LBKJL86x2Xqc9h20uyd4upWg1tZmQdbyWKdoZ0Tq/kJBCEiKysMXfQxHvBICIc552oWMz9eTtprBfzQW8hHeWbsV303BwkJAckPuGelnPn9uJU8jTVzEcSvt/dDh3Xq1GnnCUsrS+jWhqFrz7BYtimE32F4zPUHqJ4z2Ijm0LuSmmZuaW8k0yqjrlgTz3EM+Tu+Jm/7IY3FVaprxg5UxzWPsRgv/BLRiZdWXs0lb3MiGL7w6SonbrrR+uZwRj9odLwQm3FETrjqED1BapQLb1RcbJboP2hLFPcfTMYdF8k=
  secret_access_key:
    secure: ORzRa6eMBaRFyZ+/yaTmTY8bbmXkEc8fVV+wnyS2RqkkLPh1lMgShW1C1YIaTWYp5Le9J+DgE5buoF4WsOGNdi6h2EDmsmrEpwj6QtPBCL5mkHg/ZMVZeCTWBEUGDE2NyKcpHg2rqN7gjPIlH+TrKvGmLxMyiQ9i5+FP7rfU3U8cQ92jGeGKJGakGqFmQBtIeKg5LvDBA7HQRyTpVpGNOx7pzZt3JhKs8u6eLulckaekwvNjuaosifebfvVA9Z0uoQoDYmQaKJwvBWd77baAbG2g2fWlXugMQxd3KLwF7Ydi8sq+VZraCCaSNbsUCX3puvWVk5ks1JPcWi6kgnPV+fHX3r9/FYS61J6/boVSf2dR2HmGPT8PyaARj5/wyKfz0JYFig6DA4x9+8kEMqVbOzIDMzWkz4Lw9+yPelHI0XihdDfWDdaJH6Mv3cwztfSqn/fxtx0qU8trWD7sTcZ/IWIhfLYqylLrnX5rIMLhhXLaGtotiTR4uGLoRDSitRB06BieBwLDYNX9zgjm+nvCI4GOBxd5W1laCVSsEbf1JPWf4LodauVNJS2ra7YGExWyCERsEblsruOz2D45uTfKL/hBdJQhXPF6clLPhQXiy8DhazKzfJ1rTE9NEVRtPbF4gBqzScXQNckcWa2oj8fR2bu7FGzGby0YIIq2OlozstA=
  bucket: dilyan-test-lambda
  local_dir: "./target/scala-2.11"
  upload_dir: travis-builds
  skip_cleanup: true
