language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
before_deploy:
- pip install --user awscli
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: script
  script: bash .travis/simple-deploy/deploy.sh
env:
  global:
  - secure: mHmoH/sr9fmICingnTBig9kcyGUgAcrCPsVpyt8TYeXzKuvupCkQQcblbGg2ybetxeiajb5MIRD5NKqUJdv8bBJY9EICabom8PRaxOqLXugdvW+AN2IRGNuTTNzMRQjzJ1+mJ8c/IydTSuiVx+MdbCfwDyFH4kpbLfwMGZxVZ7Y/Rk0oHXn4Rtsmj8pFPy/qOkt3QOrIp1c0q9X9k8voLBBl8n5T8KOqG2oLjtkJDSUpZ5otEwyMlFS2F4dNubksiIk5h7c0hHlsTrrSsjNz4Cm7w+K3VC3Oq/C3Kpl8TVIgCG+Epk2TtQAVA8qncqHaEPXLWQD9PTVKsYh//8LPAj4/NKzBj7wBZZKfOlwTpVajWAs6eDaEoNgg35fHjHD85gVZ+LAF5tM6MO+1Sd9pIEMb4qba58CTqhL6dkUy7NYzQrle5GqTjfUPav2yYWbZn28DbyplCYu4yfA6FAABAY5XjPpcLUdyVDhQhAThsjOfKFAOzFcPpYdvoFFBYNt5l6iuSo36qo35tFpSi9XyuzdYak823tHzFH1vKz8TBwKnkz+gF5FArmlZkeqAM9M+MPVRyD/W8+WfjH8WjUR6Hi8dK4t+wS0Oo6Nn2zSTFaOn5J1Y7OjmuJKPTWqqc7u7ZbGbrHDmYz2kUjVEjQc36Lo0Lrjh6UtvikeiGkV9Ets=
  - secure: oPPkToE6aOArIO2iesfIUs/0984NmkqgeC7oAOVhsie62CH4u4YgzE9H+8e5KVStKAmet+PXwGR62HSP2zO3TVGSjOImmhoiW83wQqdIq1KmcA3PbwVPZC/BVN7/7XW4YUx6g8IPReZR8qKOGAki0bNcybQcVeojtyp3Ae+O/Djj29ZLzgj/LO4FgV0KXRWtA7a1n1FsufBX/LmBeBrtFqDqfNPTkRu6C+qAi6V/QOvIIu8LzGcdo/RWw/wW7Sfyg3WiblSesa50xvX6VtlYH+mCvf7wZ+MYT+n2c3xGKKoDe/5N0UE1KsyzPn+f8vkpzTbM5rF/oX4ite2R4O3jDLkiHGOBjdvJKTLg7OMNWMXCMiUSrb8ASRFkNAIS7KeJwb6cop063t3VpJAcXVd4DypNEdtNwuXSafrUsKZ80Sp9GvMIwY3UHTWLL0LYPUxWmV0JEhU2JGoRN+ievgnTyWWVnQ/k25ho+6+pt+V9LjYGruV+USi4+82B8Ysh9Dz0O/tJ9XEUrJB+RCZ4xGGqNK11XQVEJE8yFfCEwHAzrTwe2h1yhAJ6p+TueBWFPEvviQYzAMOHiyTwvJYhhl070ZVvnQKZZCRuVaTPPS2s/jj1H4f9DzvGnZ/+dNlmtg5EZA5Lp7kFjJthDfXmtOwHObifjjynFVEjxaQMqnHhWvs=
  - secure: itZ+ciXprlI905MeI7Lb7agZLwnsX04djXOkLoWUn6SSDl1uCps9CLdqOde+Pd2n/pFyJJYdqkqxJYq5+uj6tyYk2efKst0Qt0ZDurXm5dpHJ8tpGQe5I+KnTxMzKP3F1VzXXWbHihy68h+cNR6m63X0+NSYTkQWYWXFgzV3Xi5klDf7Pn2kKnAitEr7ndehVJKLMpaucXgzZKmPG5ofKiS97w1YYDyKJF+tDUCtmYx0hnv7nf7SPduhdBo0+2ils51Kg8fXG+LLwYqG8URDUJKxtbUiiNMwQo4sn1TW4jeNPhuGjFF6hZMpHOrLXhRzC1BfWbsumY1TAI5s73hsqjAAJ3dlJsz7HwIAAJLITTWyvz53cUBT4RecqkY/17hMJxDU8z/dHqDL2L5bVtELy942jQRPlCybWg+IqIVnx94wnt2wMuG7VbVRYX49cCoNhH50c3SIXQHX7oBnNTxjKIdPJlq+du0V/Qh7buRV0vOsf2x7iSTxyMQ00TzoY1UUm0tpwK6OTnKoA9AeQT2A25rsX8NyYtD61P3WrnzouJEAgb+nFCrsPg+y5McKN1NX9o8UgUREeHFuTWyVwxswSr5iKSjDu4HwivucnLmMQ1IZCAEIN8o12A4GJwRJlq8n4/Mfcjv0XR7+g8t/RWEqfdO9wSJo7iKIG3O4/wa+fIg=
