language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
before_deploy:
- pip install --user awscli
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: script
  script: bash ./dilyan/tofee-box/travis/simple-deploy/deploy.sh
env:
  global:
  - secure: o/cAHGjwX+y2B7LE/bO7nY72mQw91ZqZE2bby0ceKiPpuBiuEol1p5IW5a8kZbt99MwRFfU2KnCBL6RRBJ3cOjPnYb181FI1MV1ytKnboAWG6r/B7kXsCC07GoSM+C9579dL2LkWKKzK3DJnUXvcFIj5+ugU5/tcpWDjW+MV5KNz0gCB6vgZnCbEPdJafbndGF5hGSSN3gPWl9arvEUnoR7w7+hp6NLnUqbXh+zwiJ0RX+EnOXNGIf9WFAB3De2kPCEyYzfrXr3K9yrv/Buf8Jmx4y4cIKCFLbKSOljqR3tGUhqlb06MFMBzoRr0jj5qwuYsERe83FRISm1LlbOyc0O/0/d59abcAPL/s/vXxYjo1Qqn6Y0gFZeSlQPsuW3MN2pmGa5+fE4lTWf/g1ZY6KpV1uNZMZ1UjutlOAmZxKjdsuDVAZVqJ0AUEYTmS4YbB5c8x6M7EX/JbTtXiV7YOUZbtGnxxQsNh6Dt6eoLIj87rB00w3ij37lWzPp5FpVACMENmG9LSTV+02NHs+xamiCI4tO2rjDAC4XfTvtOn84TEwVMims4uHpkWpSAipfNhNgszBbD46CW0RGjumu61bQ3rmK8wzHsn75rHoMGBYFCa8bAVcTcPtPD27BIS9ID/G5obRDEqclBSg6Epv+sNTMoIabRQS4aalXRBEfBclI=
  - secure: VZ2+7bnCzzw828e3gTySWZA3EMLPriOQOhYjRyBjgNXVoN8DaMz18muk4KH9u+w/v2nULNv0aWXkdF3OJFO4Gc4sfz70M0xQFmKn/f3rAgpXcmlowR9a2DtQtoJQBfD8lgvLXBWi0ghF0Akg625IGx9QWEtylVTuuVJNFfSoV7ExVWy7VFOHcXBjFvKLhJ2Rsu1HSYfsWJl/Dj4gd+g/eJixDZNjrpkLFda3Z2QsRlkT8fQCV/0UVzKn6d23excVl7c6CNZsq8z0iq4Q2RhWqFA+oaB7y+cjStkTBCpsVe1oF930j2Giwr6PxNUAYwfYhEcvZQbajJgrIRhnRRGuhnhJulZ8S8eVPtz4s0G448teulfvMPJ/NxD77Ua3FyUPon4egN1H2UJvm6yP1qfOh1g0vtQm0o/97pBohVWV52UDBeUrANfBO95JICNZ3xoRjofdkHkjRAvKLDFIRdwSinkuLitM8ZT6if7iKTz4QR2WbXeacaKJTio/xFYzx88Rb+jiS0Le7Rj3dszcYCoiWDsnVU0p4joUkx2f5MrO6DFB50KJA6GsVse3v/pW5/N2JelQN/MFDy3PLJhNJFUMgpS5rrqMJU5tZQ1PfR+kDC7Nc/gfL0vQScNKY7wKuLA+t/DJ4lg/kDzWRtoFO5WCUK7M/B8GlkQcBH9DgMXAH2c=
  - secure: fv7SZPN/0+1YwnTSyVg1cL+N3WjUplPEt1d0hHg9IP1SCTOOd2BVUMiHBuHcSSGHLxACuF3hUpQ3uqwXc4JG3zJ1kCdjkPdtw0e7DGPFYbg4Ski8uUL71QgMxuOIBPW3Jpm8aJNGMtAhedr5rDIjAZhYgfyIkm5oEdIm48qNEieh3qk3wP64kDtOoA1fGPqK9gSRG7aHzdpq3oAWlKzyWHa6uLrYZa3HS9WEaYo0HWSySxn6gkFFYGtrE2/kp7DxDS747J/qImmzgOokqTorKRSrQL67nBTZhn07qvuplfOZJO2xJopGj280pDZYmL7KbpHJaASm9jl2s1VuyfL1nkk0mUi7PwjSY/v6LhcMs0FLPtirHu+yPKpY6peNp0LbMEVJ/lKOu+tqKFc5CspLBYQ7W2QMMd9EnBIJfAw7rDMfGWFh0jXm6+zy4J/wjbZl23ZtG+UojHOm3j/AKnXotelCSo9s+nper2snEyEipjH0gezSCHb7Aq260ozRiEvhgDRGKSIzaP13SPp+jT8W40o9FiukFBHcA0gMl+3Zxx9aH8cAg2R5tgPDvW3Am7IIyaR/Q4M4DaaBEYIAmuqvykJ6KXzQiMaGHf8ahOt1+MtrLyMJTjYJlnmDsbWo0JWCh1jSWgiMhL1h+cV/mBLY4ZNfdqfwV+WatrZukO65h5w=
