language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
jobs:
  include:
    - if: tag IS present
  exclude:
    - if: tag IS blank
before_deploy:
- pip install --user awscli
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: script
  script: bash .travis/simple-deploy/deploy.sh
env:
  global:
  - AWS_DEFAULT_REGION="eu-west-2"
  - secure: bL71PPnXwE9qjESBq0AMnwyBh/IDHkV+DfWqVQVmUDzkg7iupgk8Fq4l0QpTEeDBTGqSPOtircfA9X28rlrxuCtZXD/mgTI3aeZJTTvVKV9rQhPYTE9VZiTchQQiRkJIq3NSu+piXLE1JiWm2csuDW6POjwcr2kOJ7osOEF1jyjOGMuI9riHBrGtK95GecrRXwi1AyUV2TT5nPKUvxo1L6CNRfe3KyABisZYwKkrVVzvIXJyq+9b+2/dro+dPKfG/CTjiawsSCJ5sh5vfXKJ/+xY84ixR12swDtMlq4TkiZzYwd45Kx1pn4eZMzhKXk6VzdONS+rPximtpe3w9Y0imvBgcGwehQsY3Yn4dLn/pFOEXxwdBEXElT8ffvy2af8FUxKhZrySX7Lw+x+mDUdkJ+51nO7l1WnQuh5yq+zEOsN3Xbf/4pKe5x8uK8pdkTWTU9NWO9PLM+iAvKL3/xh75bQwKNCeds1DMtRpoLcSZcygBBtKh57lhp2YnKcNFA9wadXpaaDZz9doRZtydXEhBqbPcYdxqbDrRgkVKd/eb7aV8xybSY+58jSrPa/H/QUk51UcSu5U45jiT1rKJowsMJlYmbjYT2qhkpD3pNGUMO3tgkifJ3XUxjTpk01ip//gGgHFpdXOySR9XRh6G5KDGf8bDe15WxG6HOEuuLNzxs=
  - secure: ADVbCW9BwQ88vffNeKRhKtvLynR/63WSmp50moZlrnSzy5mPL61L3XJaSkh4vFdU42iqipfMz8lIg7XXN/lYwigwkG/WZVEbSPgB1PLURvi/CRQEsRKUODqCe1kFilmjdBulzuiSHu7XCEsMknhHBvnHw+BARgQTh5fB625Qxmhm7snTjIv7Zs/q1PIEMujL95Wh3BogeqPh9W7WW+aecMCyMwho6RN3Dem40KXQkNypBV1NHKZqcxjW0t+09885oWRUsgHGyNa2wSPsJ2dW25DW5LXSfZhSbZ3oQjy4hIf5EYxyIQRwnwcZ/LtGkGJgTSBkRIUR98uaS9+V/WOSJrlxa/YNggC5Qk2M+cjYZWNgyczjmQ1nrdoddiigjw+o9laP69Drc2VwqRrPeSJqC+naSTX1ZnL79xp8lRF3Jea/faFLdPVb/4G9ylmHXmTjLp2SJkEoRj88JNni53bAiAPImbB+RzOARpqJjF1NOL275INN4/dXUlt2DTJr0Arno83auBQvI4fIKenZs4ksy2lrjhhMirfYb5ep869/Ttm+VJm2jBAVGIgTZQGazVFBWs9YTdy5tQc6267sXcsc1JLGdk9po+7F7sn/pJaTJhkEjAuyRpkkH1WB11OswR6zzKjFx1EZ57Cq1BxfiVrEilpztWCYxiFJCo1lHy98aHQ=
