language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
before_deploy:
- pip install --user awscli
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: script
  script: bash .travis/simple-deploy/deploy.sh
env:
  global:
  - AWS_DEFAULT_REGION="eu-west-2"
  - secure: "Tf4lhOjl4rONDSslR1pHGtMxfCLKgZ/SiOyPHjTtQKIE7fg8tCJpL6Wy9/ein9cPkF/llnQDSyAlIgF5ts5xMLLxyE1ymiLVuqEb7emHwuD7T8AHJD+9q3H9WViV4q41GMf1rkOYJZT8Xu65vvh3ojicTOyA2ul3Ux3siddqUwP5Rtbu+bLvepFyW8oAVpu3igW/nlI5cKK5kbC85lMW611JvRsl3l1ebzoc270WkktzTAp2oUeFfobnEOh8mtMBk5ICJkFwxwV/RmrGtIyGBUvgYjoIOhIXby2TMuuyG0Dcd+W1pn+wT60oaf8NU9evsUbuFELGjs/eRznU7VACMFvBEFneg3XZHMBrC4D1fVHkvxgIlluAMgs8KGijFHup3pncGmRYF5tx3BUzs3dCsbixO91HNgH+fzoqy9/2t3aM3X4MiWVZwhCsQ2cMVotbsmayKTWsbssolwo3C9468sipZY6AUQW/tesWbD/orQgZZAxBCR3Q/nf2m6cFWjLDr0jh/Jb3yRyliId3C7nBubU4O9Ez7xQrjVlulgfO6NybOdUMcOVXIpfF7QstLu5JJIshVyZPjgdHt9h6uHhBlcvO/5U8Ks0QSnOjHIoqrmmj2rOfYzoVzpsyuu/hXqPWGpy9cAj/HvZEcIx+AMaoCRIdlW7V0dQvHK3qXnS800E="
