language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt test
before_deploy:
- pip install --user awscli
deploy:
  on:
    tags: true
  skip_cleanup: true
  provider: script
  script: bash .travis/simple-deploy/deploy.sh
env:
  global:
  - secure: CJ/o0lC75PvRLo4SxKdXZ/pQZpi+hzLDGkSKmlmROAiBqJDZ172ffKLjFnHFfNdXEASyTsB6TheE5ieWHT3S8bvt6BfWYty9wpNBCutWUbmi2UruaPW1/1L1Z23SxW0eL8Aqyz4QUnymAsveMGun9fOdhpiTRL2XA6LGc1yLUOHMb9rkxoTJqSgvpG91XL9R6H1BgYHbK4q9C3W0OSGBQP11Havw/zhTaui40P+zSrh3H5lY4R/oDO2ZTaueJZioDMtzVE9DKMH9rGCUTU0Y4R4NdJcwKC/9ez1MiK2cjrYzCnCKNcygW5/I82EdrLoj2hUvEWks7mYr7u5fHlcA4hvtJh27WM1GsQ+N8l5LxRFcFH4jnZ/n4KgCrmI6XzpxjM/k0HiKIFL9JC8X5zvSlJ9Nzoc81nn7NdW6XasyBuP8+BUh+MHIeBZD2K+r3AWWxfZAccrutmt5L4oC3/bLswnmDxwBPufgdQOo9gTrezH6lmH5tq8k6kv9YFbc/CTH/04Q3jy9w3MHJlz+uoWSTPgzDL732QM2zSj7vBFRZ4kHTQHu90FYlt2Fd0iWwr9MsY/023P1iJO2zZSgnlvOuyBFomIu8Xi/3kR6D8k8CQ/tB6VTXe37CK2QsXu9JR3LjD8p//eRPnnLfhaOha+Oibg3tVvx0BT1/C3ySYHw+TM=
  - secure: PJ0ypXU5tl0k4M2oTaGunmekw21b7lwu3iPqgFFcJ37/TFQZgmIsJrmeiESCtJKYtPaAVNwPARBigqU54KOH7tu1CO4NLb7aRg5bq7AqxUkWUcCPDM37V42Zouz0dChrQ0v1PxqIMS7a3UN0B+QfavJzurAz1rJK9uGRq0brURVcK9yhBLVAH6qhrXs8X5Q6al3gfWNnqlqeig9fST3eSZJwjO477nK7A0/bWhecgz5m6ZsrRHrNgDX0EnrN3H9s/NcQBnWvXuoCHl6AFHa9EgZ6zud9uS5pzvbBN/CsnM+blb1F5DxVLbfL4hZF8TfRNU8k10JUGFIu6bv1pSY5csN/5K8NiYsfEyFMVkAfHSgp4vBKzP5CHOM7ghcl5zpMNXKCDS4LylQlqxgBclEXXgXB6UoJibojJ2cnMAQQVHSVVF/98mn02QO/A4E0B02kkDCeGHDVJT6+dYb4bLRf3glNIM4LmF/IOMIbeQeG3KXa2HcO9HsFabKedUnDRPmOdD0vjqH3gpilfAX2YV871NgS8rPybsp2L3EvvbAt7c/XsB3xdbOxgZG/ylbYo40/5FxXgF3dI9//y221q1y58Zq15hGDz3EvdqsPqOVqN0/nvB5QRWgRgGUzQYJSUl8iDnu9jiI34+TGQpp9chNQSNO5l9k4SXVkzwpgCHMT4Bo=
  - secure: ADPGOJ18wJHeKlrjUfRQj2dmJ0HqQYpg1L8D1GArD2sCbeSpohuZ/MezCWWOqtrQLx3pCB3naWpEP8k9DpseeOTlRgrhBtstX5hhz782LRnvSKlwHIXlpndDwfp9ot3TpgU45dAjt0vuYF/22WrvL1FHFzhPVXrgAuqhw57E2UYzckJFY2ZqFF3Wg+yeDAhIqvezY3Lz2UZnXn8zV96NvulgOUQuUDMHHBYIc2KVBdMg5Gbw4glLis/Y7z2QGCTxQgJGIuZoTG24m5gLu4sSOZbhaaTX23djp58BQMBJWEh0bcUYBzfSil5/R5nxYuOov/icCLX4RJPMIgjaaMToBUp3pUQiUIyrtbL/jWbtw3Nm+RLTUnP1n7c21vIFRakT1Ohnl67wLLMDQc3OhqolNqH1+kNXpIAiCy8LYpddl+PBwjBngg/ru9xiqanVoPTrp5/bbljTxiHrrweOFWwXRlGvmVBoeqnYIIRZlIKCA+urotPdfKJlzjgwYQ7u/+pWXY2iuM8YAcWm0yEFOCzr9QvGSheeGPCLyEA9/IAbWNIA82Zra52iWBdClsR4VzqjoDjSnZQnTXTtbj3SHfoTcNxf4FzxX+UtCIYvhV3FaeUeTJ34o4Emd27/oFodOD+bSYvA4j5DgJ71LJ2e0ywmdh6ooL6GbkaRBbQg+LwaH2I=
