#!/bin/bash

set -e

cd $TRAVIS_BUILD_DIR
pwd
echo "TRAVIS_BUILD_DIR: $TRAVIS_BUILD_DIR"
echo "TRAVIS_BUILD_ID: $TRAVIS_BUILD_ID"
echo "TRAVIS_BUILD_NUMBER: $TRAVIS_BUILD_NUMBER"
echo "TRAVIS_BUILD_WEB_URL: $TRAVIS_BUILD_WEB_URL"
echo "TRAVIS_COMMIT: $TRAVIS_COMMIT"
echo "TRAVIS_COMMIT_MESSAGE: $TRAVIS_COMMIT_MESSAGE"
echo "TRAVIS_COMMIT_RANGE: $TRAVIS_COMMIT_RANGE"
echo "TRAVIS_EVENT_TYPE: $TRAVIS_EVENT_TYPE"
echo "TRAVIS_JOB_ID: $TRAVIS_JOB_ID"
echo "TRAVIS_JOB_NAME: $TRAVIS_JOB_NAME"
echo "TRAVIS_JOB_NUMBER: $TRAVIS_JOB_NUMBER"
echo "TRAVIS_JOB_WEB_URL: $TRAVIS_JOB_WEB_URL"
echo "TRAVIS_OS_NAME: $TRAVIS_OS_NAME"
echo "TRAVIS_OSX_IMAGE: $TRAVIS_OSX_IMAGE"
echo "TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST"
echo "TRAVIS_PULL_REQUEST_BRANCH: $TRAVIS_PULL_REQUEST_BRANCH"
echo "TRAVIS_PULL_REQUEST_SHA: $TRAVIS_PULL_REQUEST_SHA"
echo "TRAVIS_PULL_REQUEST_SLUG: $TRAVIS_PULL_REQUEST_SLUG"
echo "TRAVIS_REPO_SLUG: $TRAVIS_REPO_SLUG"
echo "TRAVIS_SUDO: $TRAVIS_SUDO"
echo "TRAVIS_TEST_RESULT: $TRAVIS_TEST_RESULT"
echo "TRAVIS_TAG: $TRAVIS_TAG"
echo "TRAVIS_BUILD_STAGE_NAME: $TRAVIS_BUILD_STAGE_NAME"
echo "TRAVIS_JDK_VERSION: $TRAVIS_JDK_VERSION"
echo "TRAVIS_SCALA_VERSION: $TRAVIS_SCALA_VERSION"
sbt assembly
aws --region $AWS_DEFAULT_REGION s3 cp ./target/scala-2.11 s3://dilyan-test-lambda/travis-builds --recursive --exclude "*" --include "*.jar"
echo "TRAVIS_TEST_RESULT: $TRAVIS_TEST_RESULT"
